services:
  cache-server:
    image: ghcr.io/falcondev-oss/github-actions-cache-server:latest@sha256:58bc6ae6fc34606c3b139e259c3c12d9ff23c793a666e8a784f13f6bb9b1aa41
    ports:
      - '3000:3000'
    environment:
      API_BASE_URL: http://localhost:3000
      CACHE_CLEANUP_OLDER_THAN_DAYS: '30'
    volumes:
      - cache-data:/app/.data

volumes:
  cache-data: